version: '3.9'

services:
  user-service:
    build: ./UserService
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development

  product-service:
    build: ./ProductService
    ports:
      - "5002:5000"
    environment:
      - NODE_ENV=development

  order-service:
    build: ./OrderService
    ports:
      - "5003:5000"
    environment:
      - NODE_ENV=development
